name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

env:
  publish_profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B38E297B2E0645B48397990896EE0F32 }}

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      
      - run: yarn install

      - run: yarn build
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          NEXT_PUBLIC_TINA_BRANCH: ${{ github.head_ref || github.ref_name }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .next

  deploy_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Deploy
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ssw-website-v3'
          slot-name: ${{ github.head_ref || github.ref_name }}
          publish-profile: ${{ env.publish_profile }}
          package: .
      
      - name: Generate summary
        run: |
          echo "Site available at ${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_STEP_SUMMARY

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ssw-website-v3'
          slot-name: 'production'
          publish-profile: ${{ env.publish_profile }}
          package: .
      
      - name: Generate summary
        run: |
          echo "Site available at ${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_STEP_SUMMARY