name: Deploy PR to staging env

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main

concurrency: ci-${{ github.event.number }}

jobs:
  build:
    name: Build and upload artifacts
    uses: ./.github/workflows/template-build.yml
    secrets:
      NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  
  set-up-test-env:
    name: Create test env
    uses: ./.github/workflows/template-create-slot.yml
    with:
      SLOT_NAME: pr-${{ github.event.number }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy:
    name: Deploy to test env
    uses: ./.github/workflows/template-deploy.yml
    needs: [build, set-up-test-env]
    with:
      ENVIRONMENT_NAME: "PR #${{ github.event.number }}"
      SLOT_NAME: pr-${{ github.event.number }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  comment_on_pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      pull-requests: write

    steps:
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: ${{ needs.deploy.outputs.url }}
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.
          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
