name: Deploy PR to staging env

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main

concurrency: ci-${{ github.event.number }}

env:
  WEBAPP_NAME: ssw-website-v3
  RESOURCE_GROUP: ssw-website
  SLOT_NAME: pr-${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    
    - run: yarn install

    - run: yarn build
      env:
        NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
        NEXT_PUBLIC_TINA_BRANCH: ${{ github.head_ref || github.ref_name }}
        TINA_TOKEN: ${{ secrets.TINA_TOKEN }}

    - name: Zip artifact
      run: zip -r --symlinks node-app.zip .next

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: node-app.zip
  
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create slot on staging site
      run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME

  deploy:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    environment:
      name: "PR #${{ github.event.number }}"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      pull-requests: write

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app
        path: .

    - name: Unzip artifact
      run: |
        unzip node-app.zip node-app
        rm node-app.zip
        ls -R

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: .
        startUpCommand: 'yarn start'
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.
          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
