name: PR - build and deploy to slot

on:
  pull_request:
    branches:
    - main

concurrency: 
  group: ci-${{ github.event.number }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build and upload artifacts
    uses: ./.github/workflows/template-build.yml
    with:
      tag: pr-${{ github.event.number }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  
  deploy:
    name: Deploy to slot
    uses: ./.github/workflows/template-deploy-slot.yml
    needs: build
    with:
      environment_name: "PR #${{ github.event.number }}"
      slot_name: pr-${{ github.event.number }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  comment_on_pr:
    name: Comment on PR
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

    - uses: johnlokerse/website-healthcheck@v2
      with:
        web-url: ${{ steps.get-app-service-url.outputs.webapp-url }}
        scan-for-text: "ssw"
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: ${{ needs.deploy.outputs.url }}
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.
          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: true

    - name: Lighthouse Audit
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: ${{ needs.deploy.outputs.url }}
        device: all
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        outputDirectory: ${{ github.workspace }}/tmp/artifacts

    - name: Upload Lighthouse artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts
