name: Template - Deploy to slot

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        required: true
      slot_name:
        type: string
        default: production
        required: false
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ steps.create-slot.outputs.webapp-url }}

    outputs:
      url: ${{ steps.create-slot.outputs.webapp-url }}

    steps:

    - name: Azure CLI - Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: AppService - Create slot
      id: create-slot
      run: |
        if ("${{ inputs.slot_name }}" -ieq "production")
        {
          # production is a reserved slot - no need to create
          $url = az webapp config hostname list `
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} `
            --webapp-name ${{ vars.APP_SERVICE_NAME }} `
            --query "[0].name" `
            --output tsv
        }
        else
        {
          # need to create slot
          az webapp deployment slot create `
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} `
            --name ${{ vars.APP_SERVICE_NAME }} `
            --slot ${{ inputs.slot_name }} `
            --configuration-source ${{ vars.APP_SERVICE_NAME }}

          $url = az webapp config hostname list `
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} `
            --webapp-name ${{ vars.APP_SERVICE_NAME }} `
            --slot ${{ inputs.slot_name }} `
            --query "[0].name" `
            --output tsv
        }

        echo "webapp-url=https://$url)" >> $GITHUB_OUTPUT

    - name: AppService - Deploy
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.APP_SERVICE_NAME }}
        slot-name: ${{ inputs.slot_name }}
        images: ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:${{ inputs.slot_name }}
